# -*- coding: utf-8 -*-
"""agent_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hMbxAvO0nzWGyBmzzHGwT9c7FD4xtE5R
"""

# --- KURULUM: Gerekli Kütüphaneler ---
!pip install -q transformers accelerate langchain-community chromadb pypdf sentence-transformers langchain-text-splitters bitsandbytes

import torch
from transformers import pipeline, AutoTokenizer, AutoModelForCausalLM
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma

# ==========================================
# ADIM 2: VERİ TOPLAMA VE BİLGİ TABANI (RAG)
# (PDF Referans: Sayfa 1, Madde 15-17)
# ==========================================

dosya_yolu = "/content/kasko_policesi.pdf" # Dosya adının doğru olduğundan emin ol
print(f"📄 Döküman işleniyor: {dosya_yolu}...")

try:
    # 1. PDF Yükleme
    loader = PyPDFLoader(dosya_yolu)
    docs = loader.load()

    # 2. Chunking (Parçalara Bölme)
    text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
    splits = text_splitter.split_documents(docs)

    # 3. Embedding ve Vektör Veritabanı (ChromaDB)
    print("🧠 Bilgi Tabanı oluşturuluyor...")
    embedding_model = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

    vector_db = Chroma.from_documents(
        documents=splits,
        embedding=embedding_model,
        collection_name="sigorta_react_db",
        persist_directory="./chroma_db"
    )
    print("✅ Bilgi Tabanı Hazır!")

except Exception as e:
    print(f"❌ HATA: Dosya yüklenemedi. Lütfen 'kasko_policesi.pdf' dosyasını yüklediğinden emin ol.\nHata detayı: {e}")

# ==========================================
# ADIM 3: REACT MİMARİSİNE GEÇİŞ - TOOL TANIMI
# (PDF Referans: Sayfa 5, Madde 114-119)
# ==========================================

def insurance_policy_tool(sorgu):
    """
    Bu fonksiyon, ajanın ihtiyaç duyduğu teknik bilgiyi dökümandan çeker.
    ÖNEMLİ: Asla cevap üretmez, sadece ham metin (context) döndürür.
    """
    print(f"\n[TOOL LOG 🛠️] Ajan veritabanında arıyor: '{sorgu}'")

    # Veritabanında en alakalı 4 parçayı bul
    results = vector_db.similarity_search(sorgu, k=4)

    # Sonuçları birleştir (Context Construction)
    ham_metin = ""
    for doc in results:
        ham_metin += doc.page_content + "\n---\n"

    return ham_metin

# ==========================================
# ADIM 3.2: AJANIN BEYNİ (SYSTEM PROMPT & LOOP)
# (PDF Referans: Sayfa 2, Madde 26-28 ve Sayfa 5 Madde 120-126)
# ==========================================

# Model Yükleme (Qwen 2.5 - Türkçe performansı yüksek)
model_id = "Qwen/Qwen2.5-7B-Instruct"
print(f"🤖 Ajan Yükleniyor ({model_id})...")

tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    device_map="auto",
    torch_dtype=torch.bfloat16
)

pipe = pipeline("text-generation", model=model, tokenizer=tokenizer, max_new_tokens=512)

def react_agent(soru):
    # PDF'teki Sayfa 5, Madde 123-126'daki Prompt Şablonu:
    system_prompt = """Sen uzman bir Sigorta Asistanısın. Görevin, kullanıcının sorularını sigorta poliçesine dayanarak cevaplamaktır.

    ERİŞİMİN OLAN ARAÇLAR:
    1. insurance_policy_tool: Sigorta kapsamı, limitler ve istisnalar hakkında bilgi gerektiğinde MUTLAKA bunu kullan.

    KURALLAR:
    - Asla ezbere cevap verme. Önce 'Düşün', sonra gerekirse 'Araç' kullan.
    - Sadece [insurance_policy_tool("aranacak kelimeler")] formatını kullanarak aracı çağırabilirsin.
    - Düşünce Zinciri (Chain of Thought) izle: Thought -> Action -> Observation -> Answer.
    """

    user_prompt = f"Kullanıcı Sorusu: {soru}\n\nHadi adım adım düşün ve gerekirse aracı kullan."

    # 1. ADIM: Düşünce (Thought) ve Eylem (Action) Kararı
    print(f"\n🧠 AJAN DÜŞÜNÜYOR: '{soru}'")

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt}
    ]

    # Modelin ilk çıktısını al
    outputs = pipe(messages)
    ilk_cevap = outputs[0]["generated_text"][-1]["content"]
    print(f"💭 Düşünce Akışı:\n{ilk_cevap}")

    # 2. ADIM: Araç Çağrısı Kontrolü
    if "insurance_policy_tool" in ilk_cevap:
        try:
            # Aranan kelimeyi ayıkla (Parsing)
            aranan = ilk_cikti = ilk_cevap.split('insurance_policy_tool("')[1].split('")')[0]

            # Aracı Çalıştır (Observation)
            # PDF Sayfa 3, Madde 70: "Observation: Veritabanından gelen sonuç Z"
            tool_sonucu = insurance_policy_tool(aranan)
            print(f"👀 GÖZLEM (Poliçeden Gelen):\n{tool_sonucu[:300]}...\n(Devamı var...)")

            # 3. ADIM: Nihai Cevap (Final Answer)
            # Bulunan bilgiyi modele geri veriyoruz
            final_messages = [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": f"{user_prompt}\n\nARAÇTAN GELEN BİLGİ:\n{tool_sonucu}\n\nBu bilgiye göre son cevabı ver."},
            ]

            final_output = pipe(final_messages)
            son_cevap = final_output[0]["generated_text"][-1]["content"]
            return son_cevap

        except Exception as e:
            return f"Teknik bir hata oldu: {e}. Manuel kontrol gerekebilir."
    else:
        # Araç kullanmadıysa direkt cevabı döndür
        return ilk_cevap

# ==========================================
# ADIM 4: SENARYO TESTİ (PDF Sayfa 2, Madde 31)
# ==========================================
print("\n🔥 TEST BAŞLIYOR...")
soru = "Aracımla kaza yaptım ama alkollüydüm, sigorta hasarımı karşılar mı?"
cevap = react_agent(soru)

print(f"\n📢 FİNAL CEVAP:\n{cevap}")

print("\n--- SENARYO A TESTİ ---")
print(react_agent("Aracımın camı kırıldı, sigorta bunu karşılar mı?"))

print("\n--- SENARYO B TESTİ ---")
print(react_agent("Kaza yaptım, alkollü değilim ama yanımda kaza tutanağı yok. Ne yapmalıyım?"))

# ==========================================
# VERSİYON 2: GELİŞMİŞ REACT AJANI (PRO)
# Amaç: Cevap kalitesini artırmak ve halüsinasyonu bitirmek.
# ==========================================

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import Chroma
from langchain_community.embeddings import HuggingFaceEmbeddings

print("🚀 PRO VERSİYON KURULUYOR...")

# --- ADIM 1: HASSAS VERİ HAZIRLIĞI (Chunking Ayarı) ---
# Eskiden 1000 karakterdi, şimdi 500 yapıyoruz ki "alkol" maddesi arada kaybolmasın.
dosya_yolu = "/content/kasko_policesi.pdf"
loader = PyPDFLoader(dosya_yolu)
docs = loader.load()

text_splitter_pro = RecursiveCharacterTextSplitter(
    chunk_size=500,      # Daha küçük parçalar (Daha keskin arama)
    chunk_overlap=150,   # Bağlam kopmasın
    separators=["\n\n", "\n", "Madde", ". ", " "] # Bölme öncelikleri
)
splits_pro = text_splitter_pro.split_documents(docs)

# Yeni bir veritabanı oluşturuyoruz (Eskisiyle karışmasın)
embedding_model = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
vector_db_pro = Chroma.from_documents(
    documents=splits_pro,
    embedding=embedding_model,
    collection_name="sigorta_db_pro", # Yeni koleksiyon ismi
    persist_directory="./chroma_db_pro"
)
print("✅ Hassas Veritabanı (V2) Hazır!")

# --- ADIM 2: AKILLI TOOL (Query Expansion) ---
def insurance_policy_tool_pro(sorgu):
    """Gelişmiş arama yapan yeni araç."""
    print(f"\n[TOOL V2 🛠️] Derinlemesine aranıyor: '{sorgu}'")

    # İYİLEŞTİRME: k=7 yaparak ajanın önüne daha fazla kanıt koyuyoruz.
    results = vector_db_pro.similarity_search(sorgu, k=7)

    context = ""
    for doc in results:
        # Metni temizleyip tek satır haline getiriyoruz (LLM daha rahat okusun)
        temiz_metin = doc.page_content.replace("\n", " ")
        context += f"- {temiz_metin}\n"

    return context

# --- ADIM 3: PROFESYONEL AJAN (Gelişmiş Prompt) ---
def react_agent_pro(soru):
    # İYİLEŞTİRME: Ajana bir 'Persona' ve net kurallar veriyoruz.
    system_prompt = """Sen 'PoliçeGPT' adında uzman bir Sigorta Danışmanısın.

    GÖREVİN:
    Sana verilen 'insurance_policy_tool_pro' aracını kullanarak kullanıcı sorularını yanıtlamak.

    KURALLAR:
    1. ASLA tahmin yürütme. Dökümanda ne yazıyorsa onu söyle.
    2. Cevap verirken maddelere atıf yap (Örn: "Poliçenin 5. maddesine göre...").
    3. Hukuk diliyle değil, müşterinin anlayacağı samimi bir dille konuş.
    4. Formatın şu olsun:
       - 🧐 Durum: Sorunu anladığını göster.
       - 📜 Kural: Bulduğun maddeyi yaz.
       - ✅ Sonuç: Ödenir veya Ödenmez.

    ADIMLAR (ReAct):
    - Thought: Soru ne hakkında? Hangi kelimelerle ararsam kesin bulurum?
    - Action: insurance_policy_tool_pro("aranacak kelimeler")
    - Observation: Gelen maddeleri oku.
    - Answer: Kurallara göre net cevap ver.
    """

    user_prompt = f"Kullanıcı Sorusu: {soru}\n\nLütfen adım adım düşün ve profesyonelce cevapla."

    print(f"\n🧠 AJAN (V2) DÜŞÜNÜYOR: '{soru}'")

    messages = [{"role": "system", "content": system_prompt}, {"role": "user", "content": user_prompt}]

    # Model zaten hafızada (pipe), onu kullanıyoruz
    outputs = pipe(messages)
    ilk_cevap = outputs[0]["generated_text"][-1]["content"]
    print(f"💭 Düşünce:\n{ilk_cevap}")

    if "insurance_policy_tool_pro" in ilk_cevap:
        try:
            # Aranan kelimeyi ayıklıyoruz
            aranan = ilk_cevap.split('insurance_policy_tool_pro("')[1].split('")')[0]

            # --- PRO İPUCU: SORGULARI ZENGİNLEŞTİRME (Query Expansion) ---
            # Kullanıcı "alkol" derse biz arkada "teminat dışı" da ekleyelim ki garanti bulsun.
            orijinal_aranan = aranan
            if "alkol" in aranan.lower(): aranan += " teminat dışı haller zararlar"
            if "kaza" in aranan.lower(): aranan += " çarpma çarpışma hasar tazminatı"

            if orijinal_aranan != aranan:
                print(f"✨ Ajan sorguyu geliştirdi: '{orijinal_aranan}' -> '{aranan}'")

            # Aracı çağır
            tool_sonucu = insurance_policy_tool_pro(aranan)
            print(f"👀 GÖZLEM (Veriler):\n{tool_sonucu[:200]}...\n")

            # Final Cevap Üretimi
            final_messages = [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": f"{user_prompt}\n\nPOLİÇEDEN BULUNAN MADDELER:\n{tool_sonucu}\n\nBu maddelere göre son cevabını ver."},
            ]

            final_output = pipe(final_messages)
            return final_output[0]["generated_text"][-1]["content"]

        except Exception as e:
            return f"Teknik hata: {e}"
    else:
        return ilk_cevap

# --- TEST ---
print("\n🔥 YENİ SİSTEM TEST EDİLİYOR...")
test_sorusu = "Kaza yaptım, alkollüydüm. Sigorta ödeme yapar mı?"
print(f"\n📢 POLİÇE GPT CEVABI:\n{react_agent_pro(test_sorusu)}")

# ==========================================
# SENARYO TESTLERİ (PRO VERSİYON / V2)
# Amaç: İyileştirmelerin sonucunu görmek.
# ==========================================

# 1. SENARYO A: Basit Sorgu (Cam Kırılması)
print("\n🔵 SENARYO A: Tek Atımlık Sorgu (Cam Kırılması)")
soru_a = "Aracımın camı kırıldı, sigorta bunu karşılar mı?"
cevap_a = react_agent_pro(soru_a)
print(f"\n📢 POLİÇE GPT CEVABI:\n{cevap_a}")

print("\n" + "="*50 + "\n")

# 2. SENARYO B: Zor Sorgu (Tutanak Yoksa Ne Olur?)
# Burada ajanın "Zabıt tutturulmalı" maddesini bulması gerekir.
print("🔵 SENARYO B: Mantık Gerektiren Sorgu (Tutanak Yok)")
soru_b = "Kaza yaptım, alkollü değilim ama yanımda kaza tutanağı yok. Ne yapmalıyım?"
cevap_b = react_agent_pro(soru_b)
print(f"\n📢 POLİÇE GPT CEVABI:\n{cevap_b}")

# ==========================================
# ADIM 5: TAM YEDEKLEME (V1 ve V2)
# ==========================================
from google.colab import drive
import shutil
import os

print("📂 Google Drive bağlanıyor...")
drive.mount('/content/drive')

# 1. Ana Klasör Oluşturma
ana_klasor = "/content/drive/MyDrive/SigortaReActAjan_Yedek"
os.makedirs(ana_klasor, exist_ok=True)
print(f"\n✅ Hedef Klasör: {ana_klasor}")

# --- KAYNAK VE HEDEF BELİRLEME ---

# PDF Dosyası
if os.path.exists("/content/kasko_policesi.pdf"):
    shutil.copy("/content/kasko_policesi.pdf", f"{ana_klasor}/kasko_policesi.pdf")
    print("📄 PDF Dosyası kopyalandı.")

# V1: Eski Veritabanı (Genelde 'chroma_db' veya 'chroma_db_final' isminde olur)
# Hangisi varsa onu alıp 'Veritabani_V1' olarak kaydedeceğiz.
kaynak_v1 = None
if os.path.exists("./chroma_db"):
    kaynak_v1 = "./chroma_db"
elif os.path.exists("./chroma_db_final"):
    kaynak_v1 = "./chroma_db_final"

if kaynak_v1:
    hedef_v1 = f"{ana_klasor}/Veritabani_V1_Eski"
    if os.path.exists(hedef_v1):
        shutil.rmtree(hedef_v1) # Eskisi varsa temizle
    shutil.copytree(kaynak_v1, hedef_v1)
    print(f"💾 V1 (Eski) Veritabanı Yedeklendi -> {hedef_v1}")
else:
    print("⚠️ UYARI: V1 veritabanı bulunamadı (Zaten silinmiş olabilir).")

# V2: Pro Veritabanı
kaynak_v2 = "./chroma_db_pro"
if os.path.exists(kaynak_v2):
    hedef_v2 = f"{ana_klasor}/Veritabani_V2_Pro"
    if os.path.exists(hedef_v2):
        shutil.rmtree(hedef_v2)
    shutil.copytree(kaynak_v2, hedef_v2)
    print(f"💾 V2 (Pro) Veritabanı Yedeklendi -> {hedef_v2}")
else:
    print("⚠️ UYARI: V2 (Pro) veritabanı bulunamadı. Pro kodu çalıştırmamış olabilirsin.")

print("\n🚀 TÜM İŞLEMLER TAMAM!")
print(f"Drive'ında '{ana_klasor}' klasörüne bakabilirsin.")

# --- REQUIREMENTS.TXT OLUŞTURUCU ---
content = """transformers
accelerate
langchain
langchain-community
langchain-text-splitters
chromadb
pypdf
sentence-transformers
bitsandbytes
torch
"""

# Dosyayı yaz
with open("requirements.txt", "w") as f:
    f.write(content)

print("✅ requirements.txt oluşturuldu!")

# Dosyayı indir (Colab kullanıyorsan)
from google.colab import files
files.download('requirements.txt')